name: delete old workflows

on:
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * 5

jobs:
  cleaning:
    runs-on: ubuntu-22.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 15
        keep_minimum_runs: 0

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 15
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
